### ISSUE TITLE
🐳 Remote interpreter support

### ISSUE THREAD

**Issue by NiclasvanEyk** [NiclasvanEyk/jetbrains-laravel-make-integration#1]
It would be really helpful to be able to use different php interpreter, for example one from a docker container.

Currently whatever `php` is set to on your command line is used, so if you develop inside a local docker container, there is a good chance that the code generation will fail due to syntax errors.

**Comment by hailwood** [comment]
It would be really useful if we could specify a command a a replacement too.
I use lando which is basically a wrapper around docker, as such when I want to execute a php command I do `lando php` e.g. `lando php artisan make:controller MyController`.

So it would be super helpful if I could just enter `lando php` as the php interpreter.

**Comment by NiclasvanEyk** [comment]
The way I would imagine the implementation, the default php interpreter of the project is used. This way you could just select the remote php interpreter inside your `php` container provisioned by `lando`.

So you could just launch the `php` container in the background, set it up as the projects interpreter, and the generation would work without needing additional customisation regarding the command.

This will only work, if PHPStorm detects the docker container, @hailwood is this the case for you if you use lando? I am not familiar with it, so I don't know.

**Comment by NiclasvanEyk** [comment]
Implemented in https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/releases/tag/v2.0.0
