### ISSUE TITLE
⬆️ Livewire / Inertia / library Support

### ISSUE THREAD

**Issue by NiclasvanEyk** [NiclasvanEyk/jetbrains-laravel-make-integration#10]
Check, whether the new Model-Factories and the new Models-default directory broke anything.

Since it now seems, that Livewire and Inertia are getting more first-party support, I want to figure out some way to support third-party make commands or at least create ones for those two.

**Comment by NiclasvanEyk** [comment]
If #11 is merged we know all `make:*` commands and their flags, so we can maybe autogenerate some entries for it.
The challenge is to find and open the file after its creation. Maybe the Jebtrains platform has an api for this...

**Comment by TheRealMattLear** [comment]
This would truly be great!

**Comment by NiclasvanEyk** [comment]
@TheRealMattLear I added experimental support for Livewire in [v2.3.3](https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/releases/tag/v2.3.3). You can directly install it from the GH releases page ([instructions](https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration#installation)) or wait until Jetbrains approves the update (usually only takes a few days).

For now, this is added only to the "File > New > Laravel" menu, after the plugin has finished detecting the available artisan commands (which can be quite slow if you are using a docker remote interpreter). So you may have to re-open your project after you have installed livewire or change your project interpreter.

I attached a demo of it running in action using Laravel Sail as a remote interpreter below:

https://user-images.githubusercontent.com/10284694/104815081-b7214a80-5812-11eb-9196-9e627b9c1a3f.mov

**Comment by TheRealMattLear** [comment]
Thanks, I've just downloaded and installed! Will let you know if i spot any issues
