### ISSUE TITLE
Add support for PhpStorm 2023.1 (EAP)

### ISSUE THREAD

**Issue by enigmatic-user** [NiclasvanEyk/jetbrains-laravel-make-integration#107]
Is a version for PhpStorm 2023.1 in the making? While version 3.4.1 is current, only version 2.3.5 is offered to me in PhpStorm 2023.1 EAP (yes, I saw https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/issues/51#issuecomment-1203152155).

No need to hurry, it's just a reminder.  :)

**Comment by NiclasvanEyk** [comment]
Thanks for the reminder, it is always nice to see that users care about this stuff :)

Honestly, I would like to have some sort of EAP channel that supports upcoming IDE versions and "beta"-stage features. There is support for this in the Gradle Plugin (see https://plugins.jetbrains.com/docs/intellij/publishing-plugin.html#specifying-a-release-channel), but I have not checked it out.

I'll leave this issue open until a version for 2023 is ready.

**Comment by enigmatic-user** [comment]
Thank you very much for continuing to develop this plugin - I'm looking forward to the new version!

**Comment by NiclasvanEyk** [comment]
@enigmatic-user A bit late, but https://plugins.jetbrains.com/plugin/14612-laravel-make/versions/stable/316304 was just released, including Support for 2023.1
