### ISSUE TITLE
Add support for PhpStorm 2023.2

### ISSUE THREAD

**Issue by walterdis** [NiclasvanEyk/jetbrains-laravel-make-integration#114]
Hi there,

I'm wondering if there are any updates planned for the new version of PhpStorm 2023.2?

Thanks! ;)

**Comment by walterdis** [comment]
> I'm on vacation and will return at the end of august. Then I'll look into it.
> 
> If anybody implements a PR regarding this I would also merge it and it'll be updated sooner.

Thanks.
Enjoy your vacation ;)

**Comment by NiclasvanEyk** [comment]
Bumped the necessary versions, ran a few manual tests on my local 2023.2 installation and everything looked fine. I released a new version, which should be reviewed and published by JetBrains during the week.

If you don't want to wait, you can download the archive from https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/releases/tag/v3.6.0 and install it from disk as described in https://github.com/NiclasvanEyk/jetbrains-laravel-make-integration/tree/v3.6.0#installation
