### ISSUE TITLE
[Critical Bug] Crashes PHPstorm if enabled and project is not a Laravel project

### ISSUE THREAD

**Issue by hailwood** [NiclasvanEyk/jetbrains-laravel-make-integration#20]
Basically the title, if you have this plugin enabled and open a non-laravel project the IDE just crashes.

**Comment by NiclasvanEyk** [comment]
Hi, thanks for raising an issue.

What version are you using? I published a fix to a similar sounding issue in v2.3.1, so maybe you just have to update.

**Comment by hailwood** [comment]
Hmm Strange, It looks like the new version isn't showing up in PHPstorm (running the latest IDE) - this is what the marketplace page shows.

![image](https://user-images.githubusercontent.com/709773/100028626-3cf8c900-2e54-11eb-8928-5ada15d51c73.png)

**Comment by hailwood** [comment]
Right you are, 

Was running 2.3.0 - Phpstorm wasn't telling me there was an update till I manually checked :)

Thanks for the quick response, and apologies for my terrible debugging :O
